#!/usr/bin/env bash
# displays information about the bestschool file.

FILE="bestschool"

if [ -e "$FILE" ]
then
    echo "best file exists"
    if [ ! -s "$FILE" ]
    then
        echo "best file is empty"
    else
        echo "bestschool file is not empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "bestschool is a regular file"
    fi
else
    echo "bestschool file does not exist"
fi
